version: "3.8"
services:
  # --- Bloc POSTGRES COMMENTÉ ---
  # postgres:
  #   image: postgres:14
  #   environment:
  #     POSTGRES_DB: bench
  #     POSTGRES_USER: bench
  #     POSTGRES_PASSWORD: bench
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  # --- Fin du bloc POSTGRES COMMENTÉ ---

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true

  influxdb:
    image: influxdb:2.6
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpass
    ports:
      - "8086:8086"
    volumes:
      - influxdata:/var/lib/influxdb2

volumes:
  #pgdata:
  grafana_data:
  influxdata: