server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/bench}
    username: "postgres"
    password: "bench"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${HIKARI_MAX:20}
      minimum-idle: ${HIKARI_MIN:10}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    open-in-view: true

  data:
    web:
      page-serialization-mode: VIA_DTO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
  prometheus:
    metrics:
      export:
        enabled: true
