startDelaySeconds: 0
lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames:
  - "java.lang:type=Memory"
  - "java.lang:type=Threading"
  - "org.hibernate:type=statistics,*"
  - "HikariPool:*"
